# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\hot_pre\denglu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(479, 328)
        MainWindow.setStyleSheet("background-color: rgb(235, 255, 228);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.login_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.login_pushButton.setGeometry(QtCore.QRect(170, 260, 151, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_pushButton.sizePolicy().hasHeightForWidth())
        self.login_pushButton.setSizePolicy(sizePolicy)
        self.login_pushButton.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.login_pushButton.setFont(font)
        self.login_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.login_pushButton.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    color:white;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #00aaff, stop:1 #a6c1ee);\n"
"    }\n"
"\n"
" QPushButton:hover{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd2f0, stop:1 #b0cbf8);\n"
" }\n"
" \n"
" QPushButton:pressed{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #00557f, stop:1 #92adda);\n"
"     }")
        self.login_pushButton.setFlat(False)
        self.login_pushButton.setObjectName("login_pushButton")
        self.user_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.user_lineEdit.setGeometry(QtCore.QRect(64, 180, 221, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_lineEdit.sizePolicy().hasHeightForWidth())
        self.user_lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.user_lineEdit.setFont(font)
        self.user_lineEdit.setStyleSheet("border:0px;    \n"
"margin:10px;\n"
"margin-left:10px; \n"
"margin-right:10px;\n"
"border-bottom: 2px solid #B3B3B3;\n"
"font-weight:bold;\n"
"background-color: rgb(255, 255, 255);")
        self.user_lineEdit.setInputMask("")
        self.user_lineEdit.setText("")
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 381, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color: rgba(234, 248, 255, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 30, 381, 281))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255,150);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(280, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.close_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.close_pushButton.setEnabled(True)
        self.close_pushButton.setGeometry(QtCore.QRect(430, 10, 28, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_pushButton.sizePolicy().hasHeightForWidth())
        self.close_pushButton.setSizePolicy(sizePolicy)
        self.close_pushButton.setMinimumSize(QtCore.QSize(28, 0))
        self.close_pushButton.setMaximumSize(QtCore.QSize(20, 26))
        self.close_pushButton.setStyleSheet("QPushButton\n"
"{\n"
"background:#FF6694;\n"
"\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background:#FF0000;\n"
"}\n"
"\n"
"")
        self.close_pushButton.setObjectName("close_pushButton")
        self.hidden_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.hidden_pushButton.setGeometry(QtCore.QRect(390, 10, 28, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hidden_pushButton.sizePolicy().hasHeightForWidth())
        self.hidden_pushButton.setSizePolicy(sizePolicy)
        self.hidden_pushButton.setMinimumSize(QtCore.QSize(28, 0))
        self.hidden_pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.hidden_pushButton.setBaseSize(QtCore.QSize(0, 0))
        self.hidden_pushButton.setStyleSheet("QPushButton\n"
"{\n"
"background:#FFDF80;\n"
"\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background:#FFC105;\n"
"}\n"
"\n"
"")
        self.hidden_pushButton.setObjectName("hidden_pushButton")
        self.label_4.raise_()
        self.label.raise_()
        self.login_pushButton.raise_()
        self.user_lineEdit.raise_()
        self.comboBox.raise_()
        self.close_pushButton.raise_()
        self.hidden_pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "登录程序"))
        self.login_pushButton.setText(_translate("MainWindow", "Log in"))
        self.user_lineEdit.setPlaceholderText(_translate("MainWindow", "Folder name"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Starch content prediction</p><p align=\"center\"> and visualization</p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Watermelon"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Pumpkin"))
        self.close_pushButton.setText(_translate("MainWindow", "X"))
        self.hidden_pushButton.setText(_translate("MainWindow", "-"))
